services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/Alibinkamal/n8n-on-render
    branch: master
    dockerfilePath: Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true 
      - key: N8N_HOST
        value: "n8n.onrender.com"
      - key: WEBHOOK_URL
        value: "https://n8n.onrender.com/"
